Update linux sunshine.desktop
LizardByte/Sunshine pull request #1768
Opened 2023-10-19 10:12 UTC by detiam

## Description

- Start sunshine by systemd service.
- Update `Categories` and `Keywords`.
- Set `Terminal` to false because sunshine now support tray.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

2023-10-19 13:04 UTC, ReenigneArcher requested changes
We have others.

- https://github.com/LizardByte/Sunshine/blob/nightly/packaging/linux/AppImage/sunshine.desktop
- https://github.com/LizardByte/Sunshine/blob/nightly/packaging/linux/flatpak/sunshine.desktop
- https://github.com/LizardByte/Sunshine/blob/nightly/packaging/linux/flatpak/sunshine_kms.desktop

2023-10-19 13:38 UTC, detiam commented
> We have others.
> 
> * https://github.com/LizardByte/Sunshine/blob/nightly/packaging/linux/AppImage/sunshine.desktop
> * https://github.com/LizardByte/Sunshine/blob/nightly/packaging/linux/flatpak/sunshine.desktop
> * https://github.com/LizardByte/Sunshine/blob/nightly/packaging/linux/flatpak/sunshine_kms.desktop

Do flatpak version support start as systemd service?

2023-10-19 18:50 UTC, kodemeister commented
I would also like to run sunshine from the main menu without terminal window popping up each time :+1:  Just my 2 cents:
- Sunshine can be compiled with or without tray icon. If tray icon is supported, we can safely disable terminal window in `sunshine.desktop` and `sunshine_kms.desktop`. Otherwise, we should keep terminal window since the user will see nothing after running sunshine.
- `sunshine_kms.desktop` still requires terminal window because it uses `sudo` to run sunshine as root. We can probably replace `sudo` with `pkexec` which requests password from GUI and makes terminal window unnecessary. But this needs to be tested.
- Is there any reason to run sunshine via systemd instead of using `/usr/bin/sunshine`? Almost all desktop files I've seen use full path to the executable.

2023-10-19 21:30 UTC, detiam commented
> I would also like to run sunshine from the main menu without terminal window popping up each time 👍 Just my 2 cents:
> 
> * Sunshine can be compiled with or without tray icon. If tray icon is supported, we can safely disable terminal window in `sunshine.desktop` and `sunshine_kms.desktop`. Otherwise, we should keep terminal window since the user will see nothing after running sunshine.
> * `sunshine_kms.desktop` still requires terminal window because it uses `sudo` to run sunshine as root. We can probably replace `sudo` with `pkexec` which requests password from GUI and makes terminal window unnecessary. But this needs to be tested.
> * Is there any reason to run sunshine via systemd instead of using `/usr/bin/sunshine`? Almost all desktop files I've seen use full path to the executable.

- done!
- `pkexec` can't keep env var, so sunshine won't work. so maybe the only way is change sunshine's code that actually need root?
- if sunshine systemd service already running and user still tries to start sunshine from the main menu, the new start sunshine will run all new startup checks then an fatal error and exit, just feel not right, try avoid it.

2023-10-19 22:12 UTC, ReenigneArcher requested changes
This PR quickly exploded... I have some concerns about the cmake changes. I just spent a lot of time organizing all that. Not saying it's perfect right now, but if there are going to be changes to I don't want stuff to just be (somewhat) randomly placed. That's how it ended up a mess of a 1000 line single cmake file before.

I also don't know if we should worry that much about versions without system tray... as all of our published packages have tray support.

And finally, while yes we do have a tray icon... I don't know that constitutes as a GUI application and Sunshine is still very much a terminal application. Due to all the various elements that Sunshine relies on, from hardware, to drivers, to other installed applications... there is a lot that can go wrong for new users. They often need to provide information from the terminal output in order to troubleshoot basic issues.

Are you on our discord server? It would be good to brainstorm and discuss this live.

2023-10-20 22:44 UTC, detiam commented
> This PR quickly exploded... I have some concerns about the cmake changes. I just spent a lot of time organizing all that. Not saying it's perfect right now, but if there are going to be changes to I don't want stuff to just be (somewhat) randomly placed. That's how it ended up a mess of a 1000 line single cmake file before.
> 
> I also don't know if we should worry that much about versions without system tray... as all of our published packages have tray support.
> 
> And finally, while yes we do have a tray icon... I don't know that constitutes as a GUI application and Sunshine is still very much a terminal application. Due to all the various elements that Sunshine relies on, from hardware, to drivers, to other installed applications... there is a lot that can go wrong for new users. They often need to provide information from the terminal output in order to troubleshoot basic issues.
 
So force tray enabled?  or we can do this 
![image](https://github.com/LizardByte/Sunshine/assets/44510779/09ccbc56-b73e-4d29-bfcd-61f083d427f1)

> Are you on our discord server? It would be good to brainstorm and discuss this live.

I'm not very fluent in English, so better keep in GitHub replies @_@

2023-10-20 22:52 UTC, detiam commented on cmake/packaging/linux.cmake
> +    include(${CMAKE_MODULE_PATH}/prep/special_package_configuration.cmake)
> I don't think we should include the same module twice.

But unless we move all these code
https://github.com/LizardByte/Sunshine/blob/e5b6a2d1eaa15dc3896f6507c97417a141a9e290/cmake/compile_definitions/linux.cmake#L162-L193 to before this module included, there are no way to detect if tray actually enabled. Maybe is good to just add `Run in Terminal` in context menu?

2023-10-20 22:55 UTC, ReenigneArcher commented on cmake/packaging/linux.cmake
> +    include(${CMAKE_MODULE_PATH}/prep/special_package_configuration.cmake)
> to before this module included, there are no way to detect if tray actually enabled.

Yea, that would require more refactoring. Not sure if you want use that approach.

> Maybe is good to just add Run in Terminal in context menu?

I think that might be okay.

2023-10-21 00:24 UTC, detiam commented on cmake/packaging/linux.cmake
> +    include(${CMAKE_MODULE_PATH}/prep/special_package_configuration.cmake)
updated

2023-10-21 01:01 UTC, ReenigneArcher requested changes

2023-10-21 01:08 UTC, detiam commented on packaging/linux/AppImage/sunshine.desktop
> +Categories=Qt;Game;
@ReenigneArcher oh I just synced with Moonlight, didn't notice. Moonlight have category `Game`, should we do the same?

2023-10-21 01:10 UTC, ReenigneArcher commented on packaging/linux/AppImage/sunshine.desktop
> +Categories=Qt;Game;
Okay... Yes, Moonlight is a Qt application and I can see how it could be considered a "game"... but I wouldn't call Sunshine a "game".

2023-10-21 01:20 UTC, detiam commented on packaging/linux/AppImage/sunshine.desktop
> +Categories=Qt;Game;
ok updated

2023-10-21 01:46 UTC, ReenigneArcher approved these changes

2023-10-25 18:14 UTC, merged