fix(Linux/Fedora): re-enable CUDA and bump to 12.4.0
LizardByte/Sunshine pull request #2247
Opened 2024-03-12 19:43 UTC by Crashdummyy

## Description
* Let Fedora 38/39 build with Cuda 12.4 which allows gcc13

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

2024-03-12 19:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LizardByte/Sunshine?pullRequest=2247) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LizardByte/Sunshine?pullRequest=2247) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LizardByte/Sunshine?pullRequest=2247) it.</sub>

2024-03-12 23:35 UTC, cgutman commented
Please also update https://github.com/LizardByte/Sunshine/blob/nightly/docs/source/about/setup.rst

2024-03-13 00:03 UTC, ReenigneArcher requested changes

2024-03-13 00:03 UTC, ReenigneArcher commented on .github/workflows/ci-docker.yml
> +        uses: actions/cache@v4
Please revert this. This file is managed in out `.github` repo.

2024-03-13 01:22 UTC, ReenigneArcher commented on .github/workflows/ci-docker.yml
> +        uses: actions/cache@v4
For the docs, you can enter this for the capability `50;52;60;61;62;70;75;80;86;90`

2024-03-13 12:23 UTC, ReenigneArcher approved these changes

2024-03-13 13:48 UTC, merged