Fix compiler warning
LizardByte/Sunshine pull request #2349
Opened 2024-04-01 22:00 UTC by istori1

## Description
Compiler warning
```
/run/build/sunshine/src/platform/linux/graphics.cpp:40:9: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
   40 |     if (!size() == 0) {
      |         ^       ~~
/run/build/sunshine/src/platform/linux/graphics.cpp:40:9: note: add parentheses after the '!' to evaluate the comparison first
   40 |     if (!size() == 0) {
      |         ^           
      |          (          )
/run/build/sunshine/src/platform/linux/graphics.cpp:40:9: note: add parentheses around left hand side expression to silence this warning
   40 |     if (!size() == 0) {
      |         ^
      |         (      )
1 warning generated.
```

### Issues Fixed or Closed

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

2024-04-01 22:09 UTC, ReenigneArcher commented
What compiler are you using?

2024-04-01 23:41 UTC, istori1 commented
Clang++ 17

There are other warnings produced. This one looks very easy to solve.

2024-04-02 00:28 UTC, ReenigneArcher requested changes

2024-04-02 00:28 UTC, ReenigneArcher commented on src/platform/linux/graphics.cpp
> +    if (!(size()) == 0) {
```suggestion
    if (size() != 0) {
```

2024-04-06 20:53 UTC, ReenigneArcher approved these changes

2024-04-06 22:03 UTC, merged