Prioritize vendored includes over system-wide
LizardByte/Sunshine pull request #3182
Opened 2024-09-14 03:56 UTC by jmou

## Description
Sunshine will still compile with the vendored headers, even if the system has its own ffmpeg headers installed.

### Issues Fixed or Closed
Fixes #3169.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

2024-09-14 04:59 UTC, ReenigneArcher requested changes
Nice, I didn't know about this option. Could you add it to the other locations where we use `include_directories` as well?

2024-09-14 04:59 UTC, ReenigneArcher commented on cmake/compile_definitions/common.cmake
> +        BEFORE SYSTEM
```suggestion
        BEFORE
        SYSTEM
```

2024-09-14 06:51 UTC, jmou commented
Would it be preferable to set https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_DIRECTORIES_BEFORE.html instead?

2024-09-14 13:12 UTC, ReenigneArcher commented
No, there's only 4 places this would need to be added, which would prevent all packagers from having to add a new CLI arg to their build.

2024-09-16 22:21 UTC, jmou commented
OK, I have updated the other locations. FWIW I think it's harmless but unnecessary on the non-SYSTEM includes, since those should not conflict with system-wide includes anyway.

2024-09-16 22:35 UTC, ReenigneArcher approved these changes

2024-09-16 23:31 UTC, merged