Options to force disable V-Sync / enable frame limiter using NVAPI.
LizardByte/Sunshine pull request #3317
Opened 2024-10-20 13:08 UTC by Unarelith

## Description
Title.

A lot of users are already setting frame limiter / disabling V-Sync in Nvidia Control Panel to reduce stutter with Sunshine.

However it would require to switch back and forth between:
- Default config (no frame limiter, vsync set to passive)
- Sunshine config (fps limit to 60, vsync forced off)

This PR aims to make this automatic.

### Screenshot
*Will provide later*

### Issues Fixed or Closed
*Will check later*

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

2024-10-20 13:53 UTC, ReenigneArcher requested changes
Thanks for the PR! this is a preliminary review.

2024-10-20 13:53 UTC, ReenigneArcher commented on src_assets/common/assets/web/public/assets/locale/en_US.json
Please update only `en.json`, not any of the other files.

2024-10-20 13:53 UTC, ReenigneArcher commented on src_assets/common/assets/web/configs/tabs/encoders/NvidiaNvencEncoder.vue
> +            <div class="mb-3" v-if="platform === 'windows'">
This one is fine, but I'm not sure why the one above is missing the conditional for the windows platform... or if any of them are even needed as the entire nvenc encoder is Windows only.

2024-10-20 13:53 UTC, ReenigneArcher commented on src/platform/windows/nvprefs/driver_settings.cpp
> +      setting.u32CurrentValue = 60; // TODO: change this according to host refresh rate
I suppose you can get this from https://github.com/LizardByte/Sunshine/pull/2894 after it's merged.

2024-10-20 15:45 UTC, Unarelith commented
I managed to try this and it worked as expected:  it changed the settings for vsync and fps limit

I'd need a bit more info on those things:
- What would be the best place to enable the temporary settings? (should be when the stream starts, but where in the code would be the best?)
- What would be the best place to reset the original settings?
- It's already possible to get the display refresh rate, how to use that in my PR to replace the hardcoded "60"?

2024-12-11 21:51 UTC, FrogTheFrog commented
>     * What would be the best place to enable the temporary settings? (should be when the stream starts, but where in the code would be the best?)
>     * What would be the best place to reset the original settings?

Take a look at my PR where the `display_device::revert_configuration();` and `display_device::configure_display(...)` are used (process.cpp, stream.cpp, nvhttp.cpp). I think those should cover all of the cases of where and how.
 https://github.com/LizardByte/Sunshine/pull/3441

>     * It's already possible to get the display refresh rate, how to use that in my PR to replace the hardcoded "60"?

I would not recommend using refresh rate, but would take it from `const auto launch_session = make_launch_session(host_audio, args);` (refer to my previous comment). It provides FPS value from Moonlight. When using the actual display for streaming I usually leave it at 120Hz, but limit FPS to 60, because for whatever reason I perceive it as a smoother stream.

It might also be a good idea to provide an override value to be used instead of an automatic one for the limiter.

2025-01-01 00:56 UTC, kirksaunders commented
I was planning on implementing this myself when I saw this PR. I can pick up where you left off, @Unarelith, if you are no longer working on it.

2025-01-01 03:10 UTC, Unarelith commented
> I was planning on implementing this myself when I saw this PR. I can pick up where you left off, @Unarelith, if you are no longer working on it.

Sure, please do.

2025-01-01 13:29 UTC, moi952 commented
> I was planning on implementing this myself when I saw this PR. I can pick up where you left off, @Unarelith, if you are no longer working on it.

Hi, if you do it, maybe it could be interesting to do it for nvidia, amd and intel? 😁

2025-01-01 21:26 UTC, ReenigneArcher commented
> Hi, if you do it, maybe it could be interesting to do it for nvidia, amd and intel?

We already have a framework in place to work with Nvidia preferences. Currently we don't have anything for AMD or Intel.

2025-03-25 07:00 UTC, andygrundman commented
Just throwing out a couple of ideas:
1. Should this also disable G-sync/Freesync? I'm not sure if these are harmful to a stream when the framerate is kept below the host's max VRR range though.
2. For the framerate limit, this looks like it uses the host's refresh rate but I think it should be based on the stream fps value. If you want to stream at 90fps for example, the 120fps host limit doesn't really help you. At the risk of making it more complicated, I like to limit refresh to -3 fps if the client has VRR so it won't exceed the VRR range. A text entry field with a good default is probably what you'd need here to make everyone happy.

2025-07-07 10:21 UTC, closed without merging