fix(confighttp): do not return 200 on errors
LizardByte/Sunshine pull request #3385
Opened 2024-11-10 00:02 UTC by ReenigneArcher

## Description

- Return 400 status code on config API errors
- Remove trailing commas in API examples
- Clarify how `index` works when saving an app

### Screenshot

### Issues Fixed or Closed

- Fixes #3384

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

2025-01-09 05:09 UTC, ReenigneArcher commented
> ## [![Quality Gate Failed](https://camo.githubusercontent.com/ce402bcc4cf818eda660128f0b27a891eb8c9f4e0d783303ea667cb0d4b07f95/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) **Quality Gate failed**
> 
> Failed conditions ![](https://camo.githubusercontent.com/bd1d5234b37410841ad8cd9d85c84eeecaec92ae18a95c926ae3a59a17c29a65/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [1 New issue](https://sonarcloud.io/project/issues?id=LizardByte_Sunshine&pullRequest=3385&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true) ![](https://camo.githubusercontent.com/bd1d5234b37410841ad8cd9d85c84eeecaec92ae18a95c926ae3a59a17c29a65/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [1 New Code Smells](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) (required ≤ 0)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385)
> 
> ![](https://camo.githubusercontent.com/0d8093b061da31b2dde5907c87c133451a9fed9ab208145ec3750960f13f438a/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6c696768745f62756c622d313670782e706e67) Catch issues before they fail your Quality Gate with our IDE extension ![](https://camo.githubusercontent.com/cf28d9441c2be84b83964b59542f8523d293ea1d96a9d3cea77e7962537f0175/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f736f6e61726c696e742d313670782e706e67) [SonarQube for IDE](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=pull-request)

Code doesn't compile with suggested change.

2025-01-09 13:29 UTC, ReenigneArcher commented on src/confighttp.cpp
> +    outputTree.put("result", "application " + request->path_match[1] + " deleted");
This fails on Unix

2025-01-09 13:29 UTC, ReenigneArcher commented on src/confighttp.cpp
> +        bad_request(response, request, "index out of range, max index is "s + std::to_string(apps_node.size() - 1));
use `std::format`

2025-01-09 13:29 UTC, ReenigneArcher commented on src/confighttp.cpp
> +    tree.put("error", error_message);
```suggestion
    tree.put("status_code", 400);
    tree.put("status", false);
    tree.put("error", error_message);
```

2025-01-09 13:33 UTC, ReenigneArcher commented on src/confighttp.cpp
>      outputTree.put("status", "true");
```suggestion
    outputTree.put("status", true);
```

2025-01-09 13:35 UTC, ReenigneArcher commented on docs/api.js
> +    curlBodyString = ` -d "${jsonString}"`;
```suggestion
    const curlJsonString = JSON.stringify(body).replace(/"/g, '\\"');
    curlBodyString = ` -d "${curlJsonString}"`;
```

2025-01-09 18:22 UTC, ReenigneArcher commented
> ## [![Quality Gate Failed](https://camo.githubusercontent.com/ce402bcc4cf818eda660128f0b27a891eb8c9f4e0d783303ea667cb0d4b07f95/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) **Quality Gate failed**
> 
> Failed conditions ![](https://camo.githubusercontent.com/bd1d5234b37410841ad8cd9d85c84eeecaec92ae18a95c926ae3a59a17c29a65/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [2 New issues](https://sonarcloud.io/project/issues?id=LizardByte_Sunshine&pullRequest=3385&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true) ![](https://camo.githubusercontent.com/bd1d5234b37410841ad8cd9d85c84eeecaec92ae18a95c926ae3a59a17c29a65/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [2 New Code Smells](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385) (required ≤ 0)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=LizardByte_Sunshine&pullRequest=3385)
> 
> ![](https://camo.githubusercontent.com/0d8093b061da31b2dde5907c87c133451a9fed9ab208145ec3750960f13f438a/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6c696768745f62756c622d313670782e706e67) Catch issues before they fail your Quality Gate with our IDE extension ![](https://camo.githubusercontent.com/cf28d9441c2be84b83964b59542f8523d293ea1d96a9d3cea77e7962537f0175/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f736f6e61726c696e742d313670782e706e67) [SonarQube for IDE](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=pull-request)

`std::format` is not available in gcc 11

2025-01-09 23:14 UTC, ReenigneArcher commented
I guess we can't return valid int/boolean json?

```json
{
    "status_code": 400,
    "status": false,
    "error": "index out of range, max index is 1"
}
```

instead of:
```json
{
    "status_code": "400",
    "status": "false",
    "error": "index out of range, max index is 1"
}
```

2025-01-10 11:22 UTC, FrogTheFrog requested changes
I mostly looked at `cpp` code. Other files seem fine.

2025-01-10 11:22 UTC, FrogTheFrog commented on src/confighttp.cpp
> +  bad_request(resp_https_t response, [[maybe_unused]] req_https_t request, const std::string &error_message) {
```suggestion
  bad_request(resp_https_t response, [[maybe_unused]] req_https_t request, const std::string &error_message = "Invalid Request") {
```

If we do this, could we perhaps get rid of `bad_request_default`?

2025-01-10 11:22 UTC, FrogTheFrog commented on src/confighttp.cpp
>    getNodeModules(resp_https_t response, req_https_t request) {
This function returns `bad_request` and could use your function perhaps? In one case it does not return anything so maybe it should also return bad request n that case?

2025-01-10 11:22 UTC, FrogTheFrog commented on src/confighttp.cpp
> +    send_response(response, outputTree);
This should be at the very back of the function

2025-01-10 11:22 UTC, FrogTheFrog commented on src/confighttp.cpp
> +    send_response(response, outputTree);
To follow the previous logic, this should be at the very end of the function.

2025-01-10 11:22 UTC, FrogTheFrog commented on src/confighttp.cpp
>      auto g = util::fail_guard([&]() {
Perhaps this one also should be removed by calling `bad_request` where the `outputTree.put("error", "...");` is used instead? Also sending a normal response in the end.

2025-01-10 11:22 UTC, FrogTheFrog commented on src/confighttp.cpp
> -    outputTree.put("status", "true");
This exclusion from the try...catch block seems strange. Could we move it at the end of the try block? Then in the catch block we would need to return.

This applies everywhere and also is just a personal preference, so this point can be ignored.

2025-01-10 13:40 UTC, ReenigneArcher commented on src/confighttp.cpp
> -    outputTree.put("status", "true");
Yes, although I didn't because I didn't think it would be likely/possible to cause an exception. I am used to more explicit try/catches instead of these huge ones though.

2025-01-10 19:06 UTC, FrogTheFrog requested changes

2025-01-10 19:06 UTC, FrogTheFrog commented on src/confighttp.cpp
> +      if (std::clamp(index, 0, static_cast<int>(apps_node.size()) - 1) != index) {
```suggestion
      if (index < 0 && index >= static_cast<int>(apps_node.size())) {
```

Congrats, c++ standard sends love!
"If `lo` is greater than `hi`, the behavior is undefined."

This will be the case when `size()` returns `0`.

2025-01-10 19:20 UTC, FrogTheFrog commented on src/confighttp.cpp
> +      if (index < 0 && index >= static_cast<int>(apps_node.size())) {
```suggestion
      if (index < 0 || index >= static_cast<int>(apps_node.size())) {
```

2025-01-10 20:12 UTC, merged