fix(process): proc status lost when streaming
LizardByte/Sunshine pull request #3417
Opened 2024-11-25 03:03 UTC by MiroKaku

## Description
Steps to reproduce:
1. Start any streaming using moonlight.
2. Return to the app selection page.
3. Open the sunshine Web-UI, delete or add any application.
4. Streaming status on moonlight has been lost.

Reason:
```cpp
  void
  refresh(const std::string &file_name) {
    auto proc_opt = proc::parse(file_name);

    if (proc_opt) {
      proc = std::move(*proc_opt); // <---- !!!! Look here, It is overwritten.
    }
  }
```

### Screenshot
None

### Issues Fixed or Closed
None

## Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

2024-12-08 15:18 UTC, ReenigneArcher reviewed
Could you add documentation blocks for the new methods in the header file (not in the cpp file)?

https://docs.lizardbyte.dev/projects/sunshine/en/master/md_third-party_2doxyconfig_2docs_2source__code.html#documentation-blocks

2025-01-21 09:54 UTC, MiroKaku commented
> Could you add documentation blocks for the new methods in the header file (not in the cpp file)?
> 
> https://docs.lizardbyte.dev/projects/sunshine/en/master/md_third-party_2doxyconfig_2docs_2source__code.html#documentation-blocks

done.

2025-01-22 16:44 UTC, FrogTheFrog requested changes
I've added some comment style suggestion, based on the feedback I've got from RA in my other commits.

Also I've found some other issues with the `env` that I would like you to fix. Sorry, that such a simple PR turned out to explode. If you prefer I can also take over the requested changes, just let me know.

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Gets the list of applications.
```suggestion
     * @brief Get the list of applications.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Gets the list of applications.
```suggestion
     * @brief Get the list of applications.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +    std::vector<ctx_t>& get_apps();
I suggest to remove this method as it is not used at all.

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Sets the list of applications.
```suggestion
     * @brief Set the list of applications.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Gets the image path of the application with the given app_id.
```suggestion
     * @brief Get the image path of the application with the given app_id.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @see refresh(const std::string &file_name)
@ReenigneArcher I thing `@see` is incorrect here as you had some special tag.

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Gets the name of the last run application.
```suggestion
     * @brief Get the name of the last run application.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +    boost::process::v1::environment& get_env();
I suggest to remove this method.

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Gets the environment variables.
```suggestion
     * @brief Get the environment variables.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Gets the environment variables.
```suggestion
     * @brief Get the environment variables.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Sets the environment variables.
```suggestion
     * @brief Set the environment variables.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @see refresh(const std::string &file_name)
Same as the other `@see` comment.

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.h
> +     * @brief Terminates the currently running process.
```suggestion
     * @brief Terminate the currently running process.
```

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.cpp
>      auto proc_opt = proc::parse(file_name);
I strongly suggest to change signature of `std::optional<proc::proc_t> parse(const std::string &file_name)` to `std::optional<std:tuple<std::vector<ctx_t>, boost::process::v1::environment>> parse(const std::string &file_name)` and also remove `proc_t` constructor as it is another disaster waiting to happen (don't forget to initialize `int _app_id{0};`)

2025-01-22 16:44 UTC, FrogTheFrog commented on src/process.cpp
> +      proc.set_env(proc_opt->get_env());
After looking into this I have found another bug related to `_env`. It is used in `terminate` function, this means we have to preserve the `_env` until process terminates :/

The moment we call `execute` we should copy the `_env` to a member variable `_app_env` (name is debatable) and replace every usage of `_env` within `execute` and `terminate` with `_app_env` (except the first one where we copy it of course). Or we could store the new ENV to `_current_env` and the in execute copy it (`_env = _current_env`). I prefer the first renaming option, but whatever is easier is ok.

2025-01-22 16:45 UTC, FrogTheFrog commented
Also @ReenigneArcher, why do we use `-1` here?
![image](https://github.com/user-attachments/assets/b0d54d2b-26ea-4260-8009-4b52d07a86e6)

Is `0` not good enough?

2025-01-22 17:17 UTC, ReenigneArcher commented
Not sure exactly where that code comes from, but 0 is the first app.

2025-01-22 17:21 UTC, FrogTheFrog commented
> Not sure exactly where that code comes from, but 0 is the first app.

But then we have a lot of places in the code checking `running() > 0` to determine if any app is running. Which is incorrect...

2025-01-22 18:49 UTC, ReenigneArcher commented
That whole system problem needs to be re-thought. As far as I see, `app_id` is not even real, it's more like an app index.

2025-01-23 06:13 UTC, MiroKaku commented
> I've added some comment style suggestion, based on the feedback I've got from RA in my other commits.
> 
> Also I've found some other issues with the `env` that I would like you to fix. Sorry, that such a simple PR turned out to explode. If you prefer I can also take over the requested changes, just let me know.

I would prefer if you could take over the requested changes. Thank you! 😀

2025-01-23 08:08 UTC, FrogTheFrog commented
@ReenigneArcher I will move some data around without changing logic too much. This should automatically resolve all of the known issues.

2025-01-29 14:02 UTC, ReenigneArcher commented
> @MiroKaku Have you perhaps unchecked the checkbox where maintainers or something can push to the branch? If so, can you enable it?
> 
> Otherwise I will have to create a fork :/

It is checked, but I don't think it allows "Collaborators" to push to.

2025-01-29 14:03 UTC, FrogTheFrog commented
I will create a fork then.

2025-05-11 10:22 UTC, closed without merging

2026-02-06 03:21 UTC, Yundi339 commented
It's a bit embarrassing 😂😂😂, our fork repository included this pr a long time ago, to solve the problem described in pr.
Since we merge it, it has been used well. Until recently I tested some special use scenarios.
I found that modifying apps in streams causes env information to be lost.
So I submitted a new PR #4654 , but I realized that there was no merge this PR #3417 .

2026-02-06 03:29 UTC, ReenigneArcher commented
@Yundi339 No worries. Unfortunately, both this PR and the replacement PR (https://github.com/LizardByte/Sunshine/pull/3604) went stale.

I would accept a combined PR that includes these fixes as well as what your PR solves, if you're willing.