Skip irrelevant submodules when building on Arch
LizardByte/Sunshine pull request #817
Opened 2023-01-23 03:57 UTC by Tea23

## Description
The ffmpeg submodules are quite large, so pulling them in when building on Arch adds some unnecessary extra time to the build. When building on Arch, we're only interested in `ffpmeg-linux-x86_64` and the others are not used at all.

Arguably we could conditionally pull `ffpmeg-linux-aarch64` instead of its x86_64 counterpart when building for / on aarch64, but because `arch` doesn't specify aarch64 as a valid architecture for this package, there's no real need.

### Screenshot
N/A

### Issues Fixed or Closed
N/A

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [x] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [X] I want maintainers to keep my branch updated

2023-01-23 03:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LizardByte/Sunshine?pullRequest=817) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LizardByte/Sunshine?pullRequest=817) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LizardByte/Sunshine?pullRequest=817) it.</sub>

2023-01-23 13:39 UTC, ReenigneArcher commented
Thank you for your submission.

> Arguably we could conditionally pull ffpmeg-linux-aarch64 instead of its x86_64 counterpart when building for / on aarch64, but because arch doesn't specify aarch64 as a valid architecture for this package, there's no real need.

I was planning to enable this for aarch64, but as far as I could find all the dependencies are not available for arm64. Perhaps I am searching wrong, but when I search for `avahi` for example, it just shows x86_64... https://archlinux.org/packages/?sort=&q=avahi&maintainer=&flagged=

In fact, arm64/aarch64 is not even listed as a possible architecture.
![image](https://user-images.githubusercontent.com/42013603/214053560-c8fa1ba1-6407-43af-a145-b376e8731a10.png)

2023-01-23 15:02 UTC, Tea23 commented
Strictly speaking, Arch only supports x86_64 and so they don't list alternative architectures on the official AUR. The `arch` parameter in a PKGBUILD specifies which architectures the package maintainer deems it to be compatible with, but the upstream distro itself will only support/endorse/etc x86_64. aarch64 and i686 are supplied by separate projects (https://archlinuxarm.org/ and https://archlinux32.org/).

Nothing stops you from defining i686 and/or aarch64 in `arch`, you just forfeit any distro level support and have to take it on yourself. If we *do* want this package to build on aarch64, we'd need to adjust the `prepare` section to conditionally pull the appropriate submodule.

2023-01-23 16:13 UTC, ReenigneArcher commented
> Strictly speaking, Arch only supports x86_64 and so they don't list alternative architectures on the official AUR. The `arch` parameter in a PKGBUILD specifies which architectures the package maintainer deems it to be compatible with, but the upstream distro itself will only support/endorse/etc x86_64. aarch64 and i686 are supplied by separate projects (https://archlinuxarm.org/ and https://archlinux32.org/).
> 
> Nothing stops you from defining i686 and/or aarch64 in `arch`, you just forfeit any distro level support and have to take it on yourself. If we _do_ want this package to build on aarch64, we'd need to adjust the `prepare` section to conditionally pull the appropriate submodule.

Okay, would you mind making the adjustment, as well as adding `aarch64` to the `arch` parameter?

2023-01-24 01:07 UTC, Tea23 commented
@ReenigneArcher Sure, although you may want to remove i686 altogether, there only seems to be x86_64 and aarch64 ffpmeg submodules so sunshine may not build in i686 at all.

2023-01-24 02:43 UTC, ReenigneArcher commented
> you may want to remove i686 altogether

That's fine with me as well.

2023-01-26 17:52 UTC, ReenigneArcher requested changes

2023-01-26 17:52 UTC, ReenigneArcher commented on packaging/linux/aur/PKGBUILD
> +        git submodule update --recursive --init
Really no point in pulling the non linux ones... maybe set those to `update=none`?

2023-01-26 17:52 UTC, ReenigneArcher commented on packaging/linux/aur/PKGBUILD
> +arch=('x86_64' 'i686' 'aarch64')
Can you remove `i686` from here?

2023-03-10 02:51 UTC, ReenigneArcher approved these changes

2023-03-10 03:29 UTC, merged

2023-03-10 07:21 UTC, KuleRucket commented
You have most commands in the if/else block repeating for every branch.

All of this could simply be outside the if block:
```
        git -c submodule."ffmpeg-macos-x86_64".update=none \
            -c submodule."ffmpeg-windows-x86_64".update=none \
            -c submodule."ffmpeg-macos-aarch64".update=none \
            submodule update --recursive --init
```

2023-03-10 12:05 UTC, ReenigneArcher commented
@KuleRucket then it would grab non architecture specific submodules in all cases.